### ISSUE TITLE
Remove the hardcode in scrape.js

### ISSUE THREAD

**Issue by developius** [YRSRevision/Refresh#13]
This code takes the points between **State the distinguishing properties of solids** and **different units and/or different linkages** which is fine for **Chemistry** but it breaks every single other syllabus. This needs to be fixed.

The code is here:
https://github.com/SubjectRefresh/Refresh/blob/stable/modules/scrape.js#L31-L51

**Comment by popey456963** [comment]
**cough** _We could just hard code every single syllabus_ **cough**

Although it's not great, I haven't seen anybody able to make any progress on this.  @developius Is there any progress?

**Comment by developius** [comment]
@popey456963 I'm working on it ;)

**Comment by developius** [comment]
This _is_ fixed but I'm holding the code back until @OliCallaghan finishes everything he's decided to do :stuck_out_tongue_winking_eye:

**Comment by developius** [comment]
Closing for now.
