### ISSUE TITLE
Revamp front-end

### ISSUE THREAD

**Issue by OliCallaghan** [YRSRevision/Refresh#14]
The front end of the site needs an overhaul, as there are out of place elements, and the website in its current state isn't very uniformed.

We need someone to go through the styling, and change it so that it looks uniform and fluid.

**Comment by developius** [comment]
@OliCallaghan I'm on it :stuck_out_tongue_winking_eye:

**Comment by developius** [comment]
@OliCallaghan I think we need to talk about colour schemes. Thoughts?

**Comment by developius** [comment]
Bump @OliCallaghan

**Comment by popey456963** [comment]
Random congratulations to you guys for creating a very slick new design.  Good job.
