### ISSUE TITLE
About 'pullup'

### ISSUE THREAD

**Issue by developius** [YRSRevision/Refresh#19]
We need to have an about page or pullup (maybe on note paper or something?) so visitors can actually see what's going on.

**Comment by popey456963** [comment]
I can work on the text that'll go inside this note/pullup.  However, my designs are notoriously horrifying for this sort of thing.  Would you think like a quick sentence thing on what this does, how you can do it, a quick demo and maybe the author names?

@developius

**Comment by developius** [comment]
@popey456963 I've done the modal (it's as it's own plugin for multiple page use) but if you could put some nice text in it that'd be great! Not techy :stuck_out_tongue_winking_eye:
