### ISSUE TITLE
Cannot Register and Add Course

### ISSUE THREAD

**Issue by popey456963** [YRSRevision/Refresh#24]
Some problem with the workflow is stopping us registering and creating a course without logging out and logging back in.

To reproduce, create a new account and try to add a course.  Server crashes and we get a 502 error.

**Comment by developius** [comment]
Has got something to do with the combination of creating an account and then adding a course.
Thanks for the heads up @popey456963

**Comment by popey456963** [comment]
Your initial fix has not worked @developius - What is different between logging in and registering in the system?

**Comment by developius** [comment]
Registering adds an account to mongo. It also (possibly - need to check) does something slightly different with regards to actually interacting with mongo.
