### ISSUE TITLE
Broke Sign In After Error Logging In

### ISSUE THREAD

**Issue by popey456963** [YRSRevision/Refresh#26]
To reproduce, login with a user that doesn't exist, go back to the main page and you see:

![](http://puu.sh/kSfZe/b791dd5162.jpg)

**Comment by developius** [comment]
@popey456963 what happens if you then click sign in?

**Comment by popey456963** [comment]
Everything works as expected, it seems to simply be a graphical glitch with how it displays.  That box is usually given when there is a character that is not in the charset.  Considering this isn't important, I'm lowering this to low-importance.  We need to get the program working first.

**Comment by developius** [comment]
I _think_ this is fixed. Please check @popey456963.
Closing for now.
