### ISSUE TITLE
Fork bomb on error

### ISSUE THREAD

**Issue by developius** [YRSRevision/Refresh#29]
There might be a little fork bomb in there...
Do NOT get your credentials wrong until this is closed.
May apply to register functions too.

**Comment by popey456963** [comment]
"A little fork bomb"...

How exactly do you get a little one?  They increase at an exponential rate >.<

**Comment by developius** [comment]
It's asynchronous too

**Comment by developius** [comment]
It appears this applied to EVERY error returned

**Comment by popey456963** [comment]
You said this was sorted.  Any news?
