### ISSUE TITLE
Validate answers

### ISSUE THREAD

**Issue by developius** [YRSRevision/Refresh#9]
There needs to be validation of the input boxes via their ‘answer’ attribute.

**Comment by developius** [comment]
@popey456963 if you don't use jQuery I'll not be happy :stuck_out_tongue_winking_eye:

**Comment by popey456963** [comment]
Working on this, somethings come up though.  If we put the answer attribute in the source of the file, can't people just "cheat", and view source to get the answers.

**Comment by developius** [comment]
I think I did it @popey456963 :grinning: except that yeah, they can just look at the source. However, as @OliCallaghan pointed out, it's defeating the object of revising. If you're cheating then you have no self control or self respect.
